### ISSUE TITLE
Примеры кода вылезают за границу листа

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngweb#17]
Необходимо исправить формат, что бы примеры кода или команды в консоли не вылезали за рамку листа А4

**Comment by trolleway** [comment]
Я так понимаю, что должно быть настроено в каких-то общих стилях latex
https://github.com/nextgis/docs_ng/issues/2

**Comment by BishopGIS** [comment]
А может просто вводом сделать принудительный перенос?
