### ISSUE TITLE
Добавить описание создания перевода в раздел по установке

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ngweb#24]
нужно сделать так:
1) source env/bin/activate
2) nextgisweb-i18n --package nextgisweb compile
3) nextgisweb-i18n --package nextgisweb_mapserver compile

**Comment by drnextgis** [comment]
https://github.com/nextgis/docs_ngweb/commit/b943a20f9a69ea1272a896f5d1ad7f257d9e9127
