### ISSUE TITLE
Добавить в установку nextgisweb_qgis

### ISSUE THREAD

**Issue by Fynjy888** [nextgis/docs_ngweb#76]
Добавьте в описание установки NGW под Ubuntu установку не только NextGIS Web MapServer но и nextgisweb_qgis, так как в http://docs.nextgis.ru/docs_ngweb/source/mapstyles.html говориться "Сейчас NextGIS WEB поддерживает две библиотеки рендеринга: Mapserver и QGIS. Обе они ставятся по желанию при установке." - что вводит пользователя в недоумение, когда он поставил всё по инструкции, а в меню есть возможность подключить стиль только mapserver и стиля QGIS почему-то нету, хотя в http://docs.nextgis.ru/docs_ngcom/source/styles.html#qgis - он присутствует на скриншотах по-умолчанию и нигде не сказано, что это модуль расширения.

В общем как пользователь советую вам добавить сюда http://docs.nextgis.ru/docs_ngweb/source/install-ubuntu.html кроме установки NextGIS Web MapServer еще и установку NextGIS Web QGIS примерно с таким текстом:
# **Установка NextGIS Web QGIS**
## Клонируем репозиторий:

_git clone https://github.com/nextgis/nextgisweb_qgis.git_
## Устанавливаем пакет в режиме разработки:

_env/bin/pip install -e ./nextgisweb_qgis_
## Переинициализировать базу данных NextGIS Web:

_env/bin/nextgisweb --config config.ini initialize_db_
## Еще раз выполните команду:

_env/bin/pip freeze_
чтобы убедиться, что ошибок нет.

**Comment by BishopGIS** [comment]
@drnextgis Это можно куда-то вставить в документацию?

**Comment by drnextgis** [comment]
Можно, только по инструкции выше работать не будет, вот тут более полное описание https://github.com/nextgis/nextgisweb_qgis/blob/master/README.md

**Comment by simgislab** [comment]
тоже не очень понял, зачем этот текст, если в клонируемом репозитории есть адекватная инструкция

но добавить в документацию наверное стоит

**Comment by simgislab** [comment]
http://docs.nextgis.ru/docs_ngweb/source/extension.html#nextgis-web-qgis
